### ISSUE TITLE
对环境有什么要求吗？

### ISSUE THREAD

**Issue by TronYY** [murufeng/awesome_lightweight_networks#3]
比如mobilenet 这几个版本 ， python 版本 torch 版本等

**Comment by murufeng** [comment]
python 3.6版本，torch--1.8.0  torch-vision--0.9.0 即可

> 比如mobilenet 这几个版本 ， python 版本 torch 版本等

**Comment by TronYY** [comment]
这些网络都能用来做什么呢  主要都是cv领域的？

**Comment by murufeng** [comment]
> 这些网络都能用来做什么呢 主要都是cv领域的？

对的，轻量级网络架构，可以直接应用到移动端部署
