### ISSUE TITLE
轻量的人体姿态估计

### ISSUE THREAD

**Issue by sayoko17** [murufeng/awesome_lightweight_networks#4]
请问对轻量的人体姿态估计有没有什么好的推荐呢？或者相应的思路优化。谢谢您！

**Comment by murufeng** [comment]
可以着重看一下这个，这是目前SOTA的网络架构方案https://github.com/murufeng/awesome_lightweight_networks/tree/main/light_cnns/HRNet

> 请问对轻量的人体姿态估计有没有什么好的推荐呢？或者相应的思路优化。谢谢您！
