### ISSUE TITLE
No module named 'light_cnns.Inception.pattern_zoo'

### ISSUE THREAD

**Issue by Nifecat** [murufeng/awesome_lightweight_networks#5]
安装好了，都能代码提示，但是导包就报错：ModuleNotFoundError: No module named 'light_cnns.Inception.pattern_zoo'

**Comment by murufeng** [comment]
> 安装好了，都能代码提示，但是导包就报错：ModuleNotFoundError: No module named 'light_cnns.Inception.pattern_zoo'

卸载之前的版本，安装light_cnns=0.4.2这个版本即可，今天已修正这个问题了，感谢指出！
